server:
  port: 7999
endpoints:
  sensitive: false
management:
  endpoints:
    enabled-by-default: true
    web.exposure.include: '*'
spring:
  datasource:
    url: jdbc:mysql://mysql.test.com/springbootdb?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    username: root
    password: 1qaz2wsx#EDC
    driver-class-name: com.mysql.jdbc.Driver    