spring :  
  redis : 
    database : 0
    host : 192.168.136.131
    port : 6379 
    password : 
    pool: 
      max-active : 8
      max-wait : -1 
      max-idle : 8  
      min-idle : 0
           
com : 
  neo : 
    title : 欢迎 
    description : Welcome 李志鹏
    




