server:
  port: 8000
  
spring:
  datasource:
    url: jdbc:mysql://mysql.test.com/springbootdb?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    username: root
    password: 1qaz2wsx#EDC
    driver-class-name: com.mysql.jdbc.Driver
    
    
logging:
  level: 
    org.springframework.jdbc.core.JdbcTemplate: debug